CREATE TABLE IF NOT EXISTS games (
id BIGSERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
description TEXT,
price NUMERIC(14, 2) CHECK (price >= 0) NOT NULL DEFAULT 0,
photo VARCHAR(127) NOT NULL DEFAULT '/static/images/default_game.png',
platform VARCHAR(20) NOT NULL,
developer VARCHAR(127) NOT NULL,
release_date DATE NOT NULL,
in_stock INT CHECK (in_stock >= 0) NOT NULL,
is_deleted BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS users (
id BIGSERIAL PRIMARY KEY,
email VARCHAR(254) NOT NULL UNIQUE,
password VARCHAR(128) NOT NULL,
name VARCHAR(255),
role VARCHAR(5) CHECK (role in ('user', 'admin')) NOT NULL DEFAULT 'user'
);

CREATE TABLE IF NOT EXISTS favorites (
user_id BIGINT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
game_id BIGINT REFERENCES games ON UPDATE CASCADE ON DELETE CASCADE,
PRIMARY KEY(user_id, game_id)
);

CREATE TABLE IF NOT EXISTS carts (
user_id BIGINT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
game_id BIGINT REFERENCES games ON UPDATE CASCADE ON DELETE CASCADE,
quantity INT CHECK (quantity > 0),
PRIMARY KEY(user_id, game_id)
);

CREATE TABLE IF NOT EXISTS orders (
id BIGSERIAL PRIMARY KEY,
user_id BIGINT REFERENCES users ON UPDATE CASCADE ON DELETE SET NULL,
date timestamptz NOT NULL DEFAULT now(),
amount NUMERIC(14, 2) CHECK (amount >= 0) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders_games (
order_id BIGINT REFERENCES orders ON UPDATE CASCADE ON DELETE CASCADE,
game_id BIGINT REFERENCES games ON UPDATE CASCADE ON DELETE SET NULL,
quantity INT CHECK (quantity > 0),
price NUMERIC(14, 2) CHECK (price >= 0) NOT NULL DEFAULT 0,
PRIMARY KEY(order_id, game_id)
);

CREATE TABLE IF NOT EXISTS reviews (
user_id BIGINT REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
game_id BIGINT REFERENCES games ON UPDATE CASCADE ON DELETE CASCADE,
score SMALLINT CHECK (score BETWEEN 0 AND 5),
PRIMARY KEY(user_id, game_id)
);